### ISSUE TITLE
T65 DI/DO Loopback Question

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/BeebFpga#17] opened 2022-02-07 21:50 UTC
More a question that an issue:

In the T65 header it says:
```
--   TAKE CARE you route the DO signal back to the DI signal while R_W_n='0',
--   otherwise some undocumented opcodes won't work correctly.
--   EXAMPLE:
--      CPU : entity work.T65
--          port map (
--              R_W_n   => cpu_rwn_s,
--              [....all other ports....]
--              DI      => cpu_din_s,
--              DO      => cpu_dout_s
--          );
--      cpu_din_s <= cpu_dout_s when cpu_rwn_s='0' else 
--                   [....other sources from peripherals and memories...]
```
I can't see this in the code. Obviously it works. Am I missing something?

**Comment by hoglet67** [comment] 2022-02-07 22:00
No you're not missing anything.

The only game I know of that uses undocumented opcodes is Zalaga, and that seems to work correctly.

I wasn't going to add this until it proved to be neccessary, as the CPU data bus is one of he critical timing paths.

I was a bit surprised though by this thread:
https://stardot.org.uk/forums/viewtopic.php?t=20350

Are you getting those artifacts?

If they occur, and this is the cause, then I have no problem adding this in. The timing is only tight on some of the older Spartan 3 targets which are rarely used now.

**Comment by hoglet67** [comment] 2022-02-07 22:15
Thinking about this some more, all of my implementations use fast asynchronous SRAM external to the FPGA, so this cpu_do -> cpu_di path does happen via the pads of the FPGA.

If you are experiencing this "vertical blinds" issue, I'm happy to add this in.

**Comment by sharpie7** [comment] 2022-02-08 20:05
I haven't seen any issue. I am using onboard RAM but I haven't checked if there is any any muxing of the signals in front of that.

I would be inclined to take an "if it aint broke, don't fix it" approach for now, but maybe add a comment next to the big statement that assigns DI to explain what's been done and why.

**Comment by sharpie7** [comment] 2022-02-12 13:58
Actually, I am now seeing the "vertical blind" effect. It isn't visible on the aliens when they are in formation, but when they dive they look like they have vertical stripes, so perhaps this loopback is needed.

**Comment by hoglet67** [comment] 2022-02-12 15:13
OK, happy to do that.

**Comment by hoglet67** [comment] 2022-02-12 15:51
Thats fixed now.

You might also want to pull in ba820f07 which fixes an issue with Pharoah's Curse.

All of the other recent work I've been doing as relates to the Papilio Duo build, so is not directly relevant to you.

**Comment by hoglet67** [comment] 2022-02-12 17:46
Do let me know if you find issues with any other games.

(I did a fair amount of testing this week against various "benchmark" games that are known to be tricky for emulators)

**Closed by hoglet67** 2022-02-12 17:46 UTC

**Comment by sharpie7** [comment] 2022-02-12 17:58
Thanks. Will do. I think we've (well you mostly) have already closed most of the bug that fraustrated me on the original MISTer version.

It seems to be a very solid emulation.
